title = "A Music Log"
description = "Thoughts on music generation, composition, and theory (news about the undertone project, too)"
base_url = "https://undertone.lfe.io/blog"
theme = "anatole-zola"
compile_sass = true
build_search_index = false
generate_feed = true
taxonomies = [
  {name = "tags"},
]

[translations.en]
about = "About"
home = "Home"
tags = "Tags"
archive = "Archive"
links = "Links"
next_page = "Older"
last_page = "Newer"

[markdown]
highlight_code = true

[extra]

[extra.content]
page_excerpts_enabled = false

[extra.show]
tags = true

[extra.social]
github = "ut-proj"
soundcloud = "oubiwann"
twitter = "lfeundertone"
instagram = "lfeundertone"
