title = "A music log"
description = "Thoughts on music generation, composition, and theory (and news about the undertone project)"
base_url = "https://undertone.lfe.io/blog"
theme = "anatole-zola"
compile_sass = true
build_search_index = false
taxonomies = [
  {name = "tags"},
]

[translations.en]
about = "About"
home = "Home"
tags = "Tags"
archive = "Archive"
links = "Links"
next_page = "Next Page"
last_page = "Last Page"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]

[extra.show]
tags = true

[extra.social]
github = "ut-proj"
soundcloud = "oubiwann"
twitter = "lfeundertone"
instagram = "lfeundertone"
